name: ls

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver-dev
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -U sa -P ${MSSQL_SA_PASSWORD} -Q 'SELECT 1' -C || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linkshortener-api
    environment:
      ConnectionStrings__Database: "Server=sqlserver,1433;Database=${MSSQL_DB};User ID=sa;Password=${MSSQL_SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./:/app
    working_dir: /app
    command: dotnet watch run
  
volumes:
  dbdata:
    name: mssql-data